name: Build master
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore cache
      uses: actions/cache@v2.1.7
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK
      uses: actions/setup-java@v2.4.0
      with:
        distribution: adopt
        java-version: 11
    - name: Build and test
      run: ./gradlew check jacocoTestReport jacocoTestCoverageVerification
