name: Pull request check
on:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test-pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Restore cache
      uses: actions/cache@v2.1.7
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK
      uses: actions/setup-java@v2.4.0
      with:
        distribution: adopt
        java-version: 11
    - name: Build and test
      run: ./gradlew build jacocoTestReport jacocoTestCoverageVerification -DrunIntTests=true
